name = "RandomGrowth"
uuid = "aabe49bf-938a-4e67-8f7d-1e52dd963db6"
authors = ["Simeon David Schaub <schaub@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
